# Generated by Django 4.1.3 on 2023-02-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passoword',
            new_name='password',
        ),
    ]
